RssAlerter.Mvc.Web/Controllers/AlertBoardAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RssAlerter.Models.AlertBoards;
using System.Web.Security;
using RssAlerter.Mvc.Web.Models;
using DapperExtensions;
using RssAlerter.Mvc.Web.Models.Persistence;
using RssAlerter.Mvc.Web.Models.Persistence.Extensions;
using RssAlerter.Models.AlertSources;

namespace RssAlerter.Mvc.Web.Controllers
{ 
    [Authorize]
    public class AlertBoardAdminController : Controller
    {
        private RssAlerterDB db = new RssAlerterDB();

        //
        // GET: /AlertBoardAdmin/

        public ViewResult Index()
        {
            var alertBoardUser = db.GetCurrentUser();

            var alertBoards = db.GetList<AlertBoard>(alertBoardUser.AlertBoardIds);

            return View(alertBoards);
        }

        //
        // GET: /AlertBoardAdmin/Details/5

        public ActionResult Details(string id)
        {
            var alertBoardUser = db.GetCurrentUser();
            var alertBoard = db.GetList<AlertBoard>(ab => ab.Id == id).Single();

            return View(alertBoard);
        }

        //
        // GET: /AlertBoardAdmin/Create

        public ActionResult Create()
        {
            var alertBoardUser = db.GetCurrentUser();

            var rssFeeds = db.GetList<RssFeedAlertSource>(alertBoardUser.RssFeedIds);

            return View(new AlertBoardViewModel(alertBoardUser, rssFeeds));
        } 

        //
        // POST: /AlertBoardAdmin/Create

        [HttpPost]
        public ActionResult Create(AlertBoardViewModel alertboardVM)
        {
            if (ModelState.IsValid)
            {
                var alertBoardUser = db.GetCurrentUser();
                var alertBoard = alertboardVM.ToAlertBoard(alertBoardUser);
                db.StoreAlertBoard(alertBoard);
                //db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(alertboardVM);
        }
        
        //
        // GET: /AlertBoardAdmin/Edit/5
 
        public ActionResult Edit(int id)
        {
            var alertboard = db.Get<AlertBoard>(id);
            //db.Load(alertboard, depth: 2);

            var alertBoardUser = db.GetCurrentUser();

            if (alertboard.UserId != alertBoardUser.Id)
                return RedirectToAction("Index");

            var rssFeeds = db.GetList<RssFeedAlertSource>(alertBoardUser.RssFeedIds);

            return View(new AlertBoardViewModel(alertboard, rssFeeds));
        }

        //
        // POST: /AlertBoardAdmin/Edit/5

        [HttpPost]
        public ActionResult Edit(AlertBoardViewModel alertboardVM)
        {
            if (ModelState.IsValid)
            {
                var alertBoardUser = db.GetCurrentUser();

                //var alertBoard = alertBoardUser.AlertBoard.Single(b => b.Id == alertboardVM.AlertBoardId);
                var alertBoard = db.Get<AlertBoard>(alertboardVM.AlertBoardId);

                db.StoreAlertBoard(alertboardVM.SetAlertBoard(alertBoard));                
                
                return RedirectToAction("Index");
            }
            return View(alertboardVM);
        }

        //
        // GET: /AlertBoardAdmin/Delete/5
 
        public ActionResult Delete(int id)
        {
            var alertboard = db.Get<AlertBoard>(id);

            var alertBoardUser = db.GetCurrentUser();

            if (alertboard.UserId != alertBoardUser.Id)
                return RedirectToAction("Index"); 
            
            return View(alertboard);
        }

        //
        // POST: /AlertBoardAdmin/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var alertboard = db.Get<AlertBoard>(id);

            var alertBoardUser = db.GetCurrentUser();

            if (alertboard.UserId != alertBoardUser.Id)
                return RedirectToAction("Index"); 
            
            db.DeleteAlertBoard(alertboard);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

RssAlerter.Mvc.Web/Controllers/AlertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using RssAlerter.Models.AlertBoards;
using DapperExtensions;
using RssAlerter.Mvc.Web.Models;
using RssAlerter.Mvc.Web.Models.Persistence;
using RssAlerter.Mvc.Web.Models.Persistence.Extensions;

namespace RssAlerter.Mvc.Web.Controllers
{
    [Authorize]
    public class AlertController : Controller
    {
        private RssAlerterDB db = new RssAlerterDB();

        //
        // GET: /Alert/

        public ActionResult Index(int id)
        {
            var alertboard = db.Get<AlertBoard>(id);
            //db.Load(alertboard);

            var alertBoardUser = db.GetCurrentUser();

            if (alertboard.UserId != alertBoardUser.Id)
                return RedirectToAction("Index");

            return View(alertboard);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

RssAlerter.Mvc.Web/Views/AlertBoardAdmin/Create.cshtml
@model RssAlerter.Mvc.Web.Models.AlertBoardViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>AlertBoard</legend>

        @Html.HiddenFor(model => model.AlertBoardUserId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RssFeedAlertSourceIds)
        </div>
        <div class="editor-field">
            @Html.ListBoxFor(model => model.RssFeedAlertSourceIds, 
                                Model.RssFeedAlertSourceList, 
                                new { Multiple = "multiple" }) 
            @Html.ValidationMessageFor(model => model.RssFeedAlertSourceIds)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RssAlerter.Mvc.Web/Views/AlertBoardAdmin/Delete.cshtml
@model RssAlerter.Models.AlertBoards.AlertBoard

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>AlertBoard</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

RssAlerter.Mvc.Web/Views/AlertBoardAdmin/Details.cshtml
@model RssAlerter.Models.AlertBoards.AlertBoard

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>AlertBoard</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RssAlerter.Mvc.Web/Views/AlertBoardAdmin/Edit.cshtml
@model RssAlerter.Mvc.Web.Models.AlertBoardViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>AlertBoard</legend>

        @Html.HiddenFor(model => model.AlertBoardId)
        @Html.HiddenFor(model => model.AlertBoardUserId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RssFeedAlertSourceIds)
        </div>
        <div class="editor-field">
            @Html.ListBoxFor(model => model.RssFeedAlertSourceIds, 
                                Model.RssFeedAlertSourceList, 
                                new { Multiple = "multiple" }) 
            @Html.ValidationMessageFor(model => model.RssFeedAlertSourceIds)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RssAlerter.Mvc.Web/Views/AlertBoardAdmin/Index.cshtml
@model IEnumerable<RssAlerter.Models.AlertBoards.AlertBoard>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>View Board</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("View Board", "Index", "Alert", new { id = item.Id }, null)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>